name: docs

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'
      - '.github/workflows/docs.yml'

defaults:
  run:
    shell: bash

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    name: Build and deploy Mindstream documentation
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - name: Install Documentation and its Dependencies
        run: make install-docs
      - name: Build docs for hosting
        run: make build-docs
      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          packages: >
            scheme-full
      - name: Build docs in PDF format
        run: make build-pdf-docs
      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: doc/output
          branch: gh-pages
          clean: true
